{{- if and .Values.prometheus.enabled .Values.prometheus.podmonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "estafette-gke-preemptible-killer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "estafette-gke-preemptible-killer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.prometheus.podmonitor.labels }}
{{ toYaml .Values.prometheus.podmonitor.labels | indent 4}}
{{- end }}
spec:
  jobLabel: app
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "estafette-gke-preemptible-killer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: "metrics"
{{- end }}
